# Generated by Django 2.2.7 on 2019-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.FileField(blank=True, null=True, upload_to='./media/'),
        ),
    ]
