# Generated by Django 2.2.7 on 2019-11-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20191129_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='um',
        ),
    ]
