# Generated by Django 2.2.7 on 2019-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20191202_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='nombre',
            new_name='copias',
        ),
        migrations.AddField(
            model_name='archivo',
            name='pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='arch',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='media/'),
        ),
    ]
