# Generated by Django 2.2.7 on 2019-12-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0017_auto_20191125_0900'),
        ('pedidos', '0009_auto_20191202_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bd.Libro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='copias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
