# Generated by Django 2.2.7 on 2019-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20191203_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='libro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
