# Generated by Django 2.2.7 on 2019-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_auto_20191203_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='copias',
            field=models.IntegerField(default=0),
        ),
    ]
