# Generated by Django 2.2.7 on 2019-12-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_auto_20191203_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='copias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='libro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
