# Generated by Django 2.2.7 on 2019-12-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20191204_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
    ]
