# Generated by Django 2.2.7 on 2019-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_remove_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
