# Generated by Django 2.2.7 on 2019-11-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_auto_20191125_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_libro',
            name='cod_interno',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='coste',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='id_modo',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='no_impresiones',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='tamaño_lomo',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='tamaño_portada',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='tamaño_portada_sangre',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='venta',
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='dato_variable',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='id_cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='id_formato_libro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='id_papel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='isbn',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='no_paginas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_bitono',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_bn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='solapas',
            field=models.CharField(max_length=200),
        ),
    ]
