# Generated by Django 2.2.7 on 2019-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_auto_20191125_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_libro',
            name='no_paginas',
            field=models.IntegerField(),
        ),
    ]
