# Generated by Django 2.2.7 on 2019-11-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0017_auto_20191125_0900'),
        ('export', '0004_auto_20191125_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_libro',
            name='id_modo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bd.Modo'),
            preserve_default=False,
        ),
    ]
