# Generated by Django 2.2.7 on 2019-11-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_imp_libro_id_modo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_libro',
            name='id_modo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Modo'),
        ),
    ]
