# Generated by Django 2.2.7 on 2019-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_auto_20191125_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_libro',
            name='id_modo',
        ),
        migrations.AddField(
            model_name='imp_libro',
            name='cod_interno',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
