# Generated by Django 2.2.7 on 2019-11-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0008_auto_20191125_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_libro',
            old_name='id_formato_libro',
            new_name='papel',
        ),
        migrations.RemoveField(
            model_name='imp_libro',
            name='id_papel',
        ),
        migrations.AddField(
            model_name='imp_libro',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imp_libro',
            name='formato_libro',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imp_libro',
            name='gramaje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='dato_variable',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='id_cliente',
            field=models.CharField(default='EDITORIAL SINTESIS, S.A.', max_length=200),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_bitono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_bn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='paginas_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imp_libro',
            name='solapas',
            field=models.CharField(max_length=10),
        ),
    ]
