# Generated by Django 2.2.7 on 2019-11-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0017_auto_20191125_0900'),
        ('export', '0011_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='cod_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='cod_interno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='dato_variable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='formato_libro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='gramaje',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bd.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='isbn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='no_paginas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='paginas_bitono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='paginas_bn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='paginas_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='papel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='solapas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
