# Generated by Django 2.2.7 on 2019-11-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0012_auto_20191127_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='cod_cliente',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='cod_interno',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='dato_variable',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='formato_libro',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='gramaje',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='no_paginas',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='paginas_bitono',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='paginas_bn',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='paginas_color',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='solapas',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='titulo',
        ),
    ]
