# Generated by Django 2.2.7 on 2019-11-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_auto_20191121_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gramaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Gramaje',
                'verbose_name_plural': 'Gramajes',
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('gramaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Gramaje')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papel_completo', to='bd.TipoPapel')),
                ('tipopapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.TipoPapel')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papeles',
            },
        ),
        migrations.AddField(
            model_name='gramaje',
            name='members',
            field=models.ManyToManyField(through='bd.Papel', to='bd.TipoPapel'),
        ),
    ]
