# Generated by Django 2.2.7 on 2019-11-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bd', '0003_auto_20191121_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramaje',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gramaje',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gramaje',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gramaje',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gramaje',
            name='uc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gramaje',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papel',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='papel',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papel',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='papel',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='papel',
            name='uc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papel',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
