# Generated by Django 2.2.7 on 2019-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_auto_20191121_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papel',
            old_name='gramaje',
            new_name='gr',
        ),
        migrations.RemoveField(
            model_name='gramaje',
            name='members',
        ),
        migrations.RemoveField(
            model_name='papel',
            name='invite_reason',
        ),
        migrations.RemoveField(
            model_name='papel',
            name='inviter',
        ),
        migrations.AddField(
            model_name='papel',
            name='mano',
            field=models.FloatField(blank=True, default=1.2),
        ),
    ]
