# Generated by Django 2.2.6 on 2019-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_auto_20191122_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tel_fijo',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tel_fijo_ext',
            field=models.CharField(blank=True, default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tel_personal',
            field=models.CharField(blank=True, default=0, max_length=9),
            preserve_default=False,
        ),
    ]
