# Generated by Django 2.2.7 on 2019-11-24 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bd', '0012_auto_20191122_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('isbn', models.BigIntegerField(unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('cod_cliente', models.CharField(blank=True, max_length=200)),
                ('cod_interno', models.CharField(blank=True, max_length=200)),
                ('no_paginas', models.IntegerField(default=0)),
                ('dato_variable', models.BooleanField(default=False)),
                ('solapas', models.BooleanField(default=False)),
                ('paginas_bitono', models.IntegerField(default=0)),
                ('paginas_color', models.IntegerField(default=0)),
                ('paginas_bn', models.IntegerField(default=0)),
                ('tamaño_lomo', models.FloatField(default=0)),
                ('tamaño_portada', models.FloatField(default=0)),
                ('tamaño_portada_sangre', models.FloatField(default=0)),
                ('no_impresiones', models.IntegerField(default=0)),
                ('coste', models.FloatField(default=0)),
                ('venta', models.FloatField(default=0)),
                ('ultima_impresion', models.DateTimeField()),
                ('preimpresion', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Cliente')),
                ('id_formato_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Formato_Libro')),
                ('id_gramaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Gramaje')),
                ('id_modo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modo')),
                ('id_tipo_papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.TipoPapel')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
