# Generated by Django 2.2.7 on 2019-11-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id_gramaje',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_tipo_papel',
        ),
        migrations.AddField(
            model_name='libro',
            name='id_papel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bd.Papel'),
            preserve_default=False,
        ),
    ]
