# Generated by Django 2.2.7 on 2019-11-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0016_auto_20191124_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
    ]
